### ISSUE TITLE
Attempted master checklist of all features from the old version

### ISSUE THREAD

**Issue by Nathaka** [dracidoupe/graveyard#199]
- [ ] - Redakční systém (content management)
- [ ] - > Schvalování děl (editing)
- [ ] - > Tvůrci a redakce (creators and editors)
- [ ] - >> Síň slávy (hall of fame)
- [ ] - Aktuality (newsletter)
- [ ] - Rubriky (sections and articles)
- [ ] - > Vkládání děl (submitting articles)
- [ ] - > Čekající díla (article queue)
- [ ] - > Novinky (recent articles)
- [ ] - > Tvorba (art)
- [ ] - >> ČaE a Hřbitov (literature)
- [ ] - >> Galerie a Fotogalerie (gallery)
- [ ] - > Doplňky (accessories)
- [ ] - > Pro PJ (for GMs)
- [ ] - > Všeobecné (general)
- [ ] - >> Linky (links)
- [ ] - >> Downloady (downloads)
- [ ] - > Postavy (characters/classes)
- [ ] - > Filtrování (filters)
- [ ] - > Hodnocení (star rating)
- [ ] - > O hlavu zlatého draka (OHZD contest)
- [ ] - Putyka (the inn/tavern/pub.../discussions)
- [ ] - > Stoly (tables/topics)
- [ ] - >> Správce stolu (table owner/topic moderator)
- [ ] - >> Ankety (table-specific polls)
- [ ] - >> Nástěnky (notice-boards)
- [ ] - >> Statistiky (table/topic statistics)
- [ ] - > Sekce putyky (subcategories)
- [ ] - > Archiv putyky (archives)
- [ ] - > Výpis hostinského (innkeeper's list)
- [ ] - Fórum (public forum)
- [ ] - Uživatelé (users)
- [ ] - > Statistiky (user profile)
- [ ] - > Popisek uživatele (status)
- [ ] - > Dračí líheň (registration)
- [ ] - > Rádci a nováčci (mentoring)
- [ ] - > Levelsystém (levelsystem)
- [ ] - > Reputace (reputation)
- [ ] - > Runy (runestones)
- [ ] - > Názory (opinions)
- [ ] - Nastavení (settings)
- [ ] - Ankety (general polls)
- [ ] - Pošta (PM)
- [ ] - > Poštovní skupiny (PM groups)
- [ ] - Chat (chatrooms and gamerooms)
- [ ] - Moudrá sova (external workshop)
- [ ] - Vyhledávání (search)
- [ ] - Rekordy a statistky (general statistics)
- [ ] - Inzerce (market)
- [ ] - Seznamka (dating/looking for group)
- [ ] - Dračí manuál (manual)
- [ ] - Otázky a odpovědi (FAQ)
- [ ] - Co je to dračí doupě? (about)
- [ ] - Psí smečka (notifications)
- [ ] - Doupě jinde (external links)

**Comment by Nathaka** [comment]
Quick notes (if you already have an issue for them or if they don't matter, just leave it or let me know):

RS - inzerce/seznamka moderator is not shown in TaR (currently PinHead), minimum half of editors is not up to date, hall of fame is getting a bit crowded (are you sure you want kamerask in there? :D)

Rubriky - there is still a huge problem with with pictures not showing in galleries and photogallery doesn't show up in user profiles (not sure if it shows in recent articles, but i think you fixed that a while ago)
- Do you still consider fixed sections for the new version? I had a very good system designed for Faleron articles based on tags, not sections, which means easier filtering, allows articles for multiple sections and even personal tags for grouping connected articles, would love to show it to you someday
-  what about allowing "versions"? meaning you could update an article based on critique and upload it as a new version or make a different versions for different rulesets/settings and switch between them - how difficult on scale from 1 to 10?

Inzerce a Seznamka - when porting to new version or even right away, could it possibly show more than 5 most recent entries?

Forum - anonymous messages yes or no? i vote yes, considering we have no other place for unregistered users to ask questions

Levelsystem and reputation - I've noticed the system doesnt do the regular weekly updates, reputation cannons are not refreshing and levels don't change - is this intentional?

PM and PM groups - messaging groups were a great idea (you basically had circles before google+), but the implementation was a bit weaker, consider making this a bigger thing.

**Comment by Almad** [comment]
Thanks! 

@Nathaka I just showed on first few items how you can do the formatting, I think it would make it more readable. 

Hall of Fame and editors will need a cleanup, but that's also for  discussions with UnknowN. 

Galleries: I know, that's waiting for me to start paying and sorting out TLS; I'll do that when we're closer to launch, trakced as #65 

I want to start with sections and no versions. Let's see whether we can make it as a feature later on, but it would be hard to make it work alongside the existing version. 

Market/Dating sure, that's already done. I want at least Dating to be redone anyway. 

Forum anonymous maybe, as a feature. Antispam is a bit of an issue. 

Weekly level system updates are not intentional, should be fixed, although I think we should update criteria very soon. Emails should be fixed first. 

PM & PM groups true. 

Merging of the FAQ/Manual possible, I'd keep the what is DrD page separate.

**Comment by Almad** [comment]
Also we have a dictionary here: https://github.com/dracidoupe/graveyard/blob/master/docs/dictionary.rst , please use it / we should update it for the stuff that's not there yet :)
