### ISSUE TITLE
The Weekend Sprint To Do 

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#370]
We should launch at the end of the weekend. What is needed? 

- [ ] Finishing registrations and registration approval #134 
  - [ ] Including sending an email
- [ ] Adding and displaying comments and ratings #102 
- [ ] Fix major visual glitches: Gallery #27 #28, user icons in phorum #369 and whatever we find
- [ ] Adding News
  - [ ] Sending news via email
  - [ ] Ability to opt out from email delivery
 - [ ] Direct Messages #354 
 - [ ] Show the Gold Dragon Contest results 
 - [ ] Proper testing of old URLs redirect
 - [ ] Put old Doupe behind htpasswd, make it possible to run it on stare.dracidoupe.cz

---
Above this is the absolute must have line. Below are things that are critical, but site is launchable without them
---

- [ ] Ability to update a personal profile
- [ ] Including an ability to update an icon #209 
- [ ] Ability to submit a new creation
- [ ] Approving new creations
- [ ] Ability to add and approve new uploadable content #99 
- [ ] Have editors #331 
- [ ] Original pagination in the Tavern

**Comment by Almad** [comment]
Sprint Almost Successful :)

**Comment by Almad** [comment]
Since it's 2 years later and given how many contributions were done both to the side and to the code, I'll now prioritize getting the switch done and getting out of tech and security debt over having the feature parity. Let's not kid ourselves too much :)
